<a href="https://colab.research.google.com/github/Asinjoji/Assessment2/blob/main/Assessment_2_Asin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [8]:
#Q1
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]
(5,)

In [5]:
arr.shape

(5,)

In [9]:
type(arr)

numpy.ndarray

In [11]:
arr1 = np.array([5, 10, 15, 20, 25])

In [12]:
#Q2
arr1=arr1+5
print(arr1)

[10 15 20 25 30]

In [14]:
arr1=arr1*2
print(arr1)

[ 40  60  80 100 120]

In [19]:
#Q3
arr2 = np.array([12, 15, 18, 20, 25, 30])

In [21]:
print('Mean :',np.mean(arr2))
print('Median :' ,np.median(arr2))
print('Min value :',np.min(arr2))
print('Max value :',np.max(arr2))
print('Standard Deviation :',np.std(arr2))

Mean : 20.0
Median : 19.0
Min value : 12
Max value : 30
Standard Deviation : 6.027713773341708

In [34]:
#Q4
arr = np.array([10, 25, 30, 45, 50, 65, 70])
print(arr[arr>40])

[45 50 65 70]

In [22]:
import pandas as pd

In [64]:
#Q5
df = pd.DataFrame({
'Name': ['Anu', 'Rahul', 'Meera', 'Arun'],
'Age': [21, 22, 20, 23],
'Score': [85, 72, 91, 68]
})
df

    Name  Age  Score
0    Anu   21     85
1  Rahul   22     72
2  Meera   20     91
3   Arun   23     68

In [48]:
#q6
print(df[['Name','Score']])

    Name  Score
0    Anu     85
1  Rahul     72
2  Meera     91
3   Arun     68

In [44]:
new=df[(df['Name']=='Meera')]
new

    Name  Age  Score
2  Meera   20     91

In [36]:
#Q7
new=df[(df['Score']>75)]
new

    Name  Age  Score
0    Anu   21     85
2  Meera   20     91

In [56]:
#8
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Column names:", df.columns.tolist())
print("Data types:\n", df.dtypes)
print("Statistical summary:\n", df.describe())

Rows: 4
Columns: 3
Column names: ['Name', 'Age', 'Score']
Data types:
 Name      object
Age      float64
Score    float64
dtype: object
Statistical summary:
         Age      Score
count   3.0   3.000000
mean   22.0  81.666667
std     1.0   7.637626
min    21.0  75.000000
25%    21.5  77.500000
50%    22.0  80.000000
75%    22.5  85.000000
max    23.0  90.000000

In [65]:
#9
df.sort_values(by='Score',ascending=False)

    Name  Age  Score
2  Meera   20     91
0    Anu   21     85
1  Rahul   22     72
3   Arun   23     68

In [66]:
#10
df = pd.DataFrame({
'Name': ['A', 'B', 'C', 'D'],
'Age': [21, np.nan, 23, 22],
'Score': [80, 75, np.nan, 90]
})

In [78]:
print("Missing values:\n", df.isnull().sum())

#setting mean as missing value
df.fillna({'Age': df.Age.mean()}, inplace=True)
df.fillna({'Score': df.Score.mean()}, inplace=True)
df

Missing values:
 Name     0
Age      0
Score    0
dtype: int64

  Name   Age      Score
0    A  21.0  80.000000
1    B  22.0  75.000000
2    C  23.0  81.666667
3    D  22.0  90.000000

In [79]:
filepath='/content/student_performance.csv'
df=pd.read_csv(filepath)
df

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6

In [88]:
#Q11
print("First 5 records:", df.head(5))
print("Last 5 records.:", df.tail(5))
print("No of Rows:", df.shape[0])
print("no of Columns:", df.shape[1])
print("Column names:\n", df.columns.tolist())
print("Data types:\n", df.dtypes)
print("Statistical summary:\n", df.describe())

First 5 records:   Student_ID            Name  Gender        Department   Age  Attendance  \
0    STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
1    STU1002    Kiran Pillai    Male  Computer Science  24.0        75.5
2    STU1003  Fathima Joseph  Female       Electronics  21.0        60.5
3    STU1004    Rahul Sharma  Female      Data Science  25.0        80.4
4    STU1005       Asha Nair  Female      Data Science  22.0        71.4

   Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0          89.4       86.3          81.9         76.7         82.7
1          70.3       63.1          65.1         62.3         60.3
2          79.9       80.4          65.3         68.0         67.1
3          65.8       50.7          52.6         48.8         57.2
4          90.1       82.9          72.4         87.7         81.9
Last 5 records.:    Student_ID            Name  Gender        Department   Age  Attendance  \
75    STU1076     Priya Kumar  Female  Computer Science  24.0        99.3
76    STU1077      Amal Kumar    Male      Data Science   NaN        93.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
78    STU1079    Meera Thomas    Male       Electronics  23.0        99.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
75          46.9       57.6          29.5         57.1         47.2
76          45.8       43.4          58.1         38.8         43.5
77          70.4       75.7          98.2         76.7         75.2
78          64.6       66.5          61.8         52.5         63.4
79          80.5       94.3          58.6         74.9         78.6
No of Rows: 80
no of Columns: 11
Column names:
 ['Student_ID', 'Name', 'Gender', 'Department', 'Age', 'Attendance', 'Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score', 'Final_Score']
Data types:
 Student_ID       object
Name             object
Gender           object
Department       object
Age             float64
Attendance      float64
Python_Score    float64
SQL_Score       float64
Pandas_Score    float64
NumPy_Score     float64
Final_Score     float64
dtype: object
Statistical summary:
              Age  Attendance  Python_Score   SQL_Score  Pandas_Score  \
count  77.000000   77.000000     78.000000   80.000000     78.000000
mean   22.012987   81.672727     72.821795   70.445000     70.365385
std     2.155126   10.054204     16.722103   14.630417     15.814294
min    19.000000   56.300000     39.500000   38.300000     25.000000
25%    20.000000   75.500000     64.525000   60.650000     61.800000
50%    22.000000   81.100000     72.000000   69.300000     70.000000
75%    24.000000   86.400000     86.525000   81.150000     82.575000
max    25.000000  100.000000    100.000000  100.000000    100.000000

       NumPy_Score  Final_Score
count    78.000000    78.000000
mean     68.574359    70.696154
std      16.417242    14.053871
min      25.000000    40.600000
25%      57.175000    60.450000
50%      70.700000    70.950000
75%      80.650000    82.275000
max     100.000000    97.000000

In [87]:
#Q12
score=df[(df['Final_Score']>75)]
print(score)

   Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma    Male       Electronics  22.0        73.2
7     STU1008     Akhil Varma    Male  Computer Science  20.0        81.1
8     STU1009      Diya Menon    Male      Data Science  25.0        64.4
10    STU1011        Diya Das  Female      Data Science  20.0       100.0
11    STU1012      Arun Reddy    Male       Electronics  20.0        69.1
16    STU1017    Rahul Thomas  Female      Data Science  25.0        78.3
17    STU1018      Priya Nair    Male      Data Science  19.0        85.4
23    STU1024  Fathima Joseph  Female          Commerce  23.0        78.2
24    STU1025     Kiran Varma  Female       Electronics  21.0        80.7
27    STU1028     Nikhil Nair  Female      Data Science  24.0        79.3
30    STU1031      Amal Varma  Female  Computer Science  19.0        86.7
33    STU1034        Amal Das    Male  Computer Science  19.0        85.5
35    STU1036      Maya Menon  Female       Electronics  19.0        82.0
37    STU1038    Kiran Pillai  Female       Electronics  25.0        85.2
39    STU1040    Rohan Sharma  Female  Computer Science  21.0       100.0
40    STU1041     Amal Pillai  Female  Computer Science  25.0        97.7
41    STU1042     Arun Joseph  Female  Computer Science  21.0        85.9
43    STU1044       Rahul Das  Female  Computer Science  22.0        70.9
47    STU1048     Priya Kumar    Male      Data Science  25.0        64.6
48    STU1049     Asha Sharma    Male      Data Science  22.0        91.3
51    STU1052      Gokul Nair  Female          Commerce  25.0        77.3
55    STU1056     Vivek Varma    Male      Data Science  22.0        81.0
56    STU1057    Rohan Pillai  Female          Commerce  20.0        79.5
57    STU1058     Diya Thomas  Female  Computer Science  23.0        83.5
58    STU1059       Anu Menon    Male       Electronics  24.0        96.7
59    STU1060      Asha Menon    Male      Data Science  19.0        56.3
61    STU1062    Kiran Pillai  Female  Computer Science  19.0        83.8
64    STU1065    Rohan Sharma    Male  Computer Science  19.0        64.4
67    STU1068        Maya Das  Female  Computer Science  23.0        66.7
73    STU1074       Anu Kumar  Female  Computer Science  22.0        95.0
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
7           72.1       80.4          72.9         73.5         79.2
8           94.8       86.0          87.7        100.0         83.0
10         100.0       93.2         100.0         89.3         91.9
11          80.4       78.0          88.9         77.1         86.9
16          80.8       99.4          77.2        100.0         91.1
17          62.6       81.6          79.6         75.5         75.1
23          87.7       71.0          88.5         74.8         83.7
24          87.5       67.1          84.5         96.1         77.3
27          70.3       82.0          64.4         72.8         77.1
30          86.9       64.3         100.0         89.2         85.5
33          94.4       81.6          71.3         81.5         84.3
35          95.3       93.4         100.0         62.5         84.2
37          87.8       78.3          85.5         82.7         82.4
39          68.9       79.8          66.1         66.4         78.5
40          94.3       91.0          73.1         91.2         94.5
41          71.2       76.1          70.8          NaN         77.9
43          68.0       67.3          83.6         76.7         77.3
47          80.6       67.0          71.2         80.2         77.3
48          88.9       95.0           NaN         94.5         97.0
51          80.4       85.3          96.7         83.5         79.3
55          87.0       95.1          88.4         75.7         93.3
56          72.1       66.9          61.8         72.3         75.2
57          93.1       78.8          91.6         83.8         92.3
58          99.7       77.1          68.9         89.7         84.9
59         100.0       85.0          87.4         57.4         87.9
61         100.0      100.0          89.4         91.4         96.0
64          96.5       69.3          86.7         80.7         83.5
67          83.4       79.6          89.3         83.6         83.7
73          95.3       67.7          92.4         81.4         83.4
77          70.4       75.7          98.2         76.7         75.2
79          80.5       94.3          58.6         74.9         78.6

In [89]:
attendance=df[(df['Attendance']<75)]
print(attendance)

   Student_ID            Name    Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma      Male  Computer Science  25.0        74.7
2     STU1003  Fathima Joseph    Female       Electronics  21.0        60.5
4     STU1005       Asha Nair    Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma      Male       Electronics  22.0        73.2
8     STU1009      Diya Menon      Male      Data Science  25.0        64.4
9     STU1010    Gokul Pillai    Female  Computer Science  19.0        67.3
11    STU1012      Arun Reddy      Male       Electronics  20.0        69.1
15    STU1016    Nikhil Kumar    Female  Computer Science   NaN        70.3
19    STU1020    Vivek Sharma    Female          Commerce  22.0        72.1
25    STU1026      Maya Menon      Male       Electronics  20.0        68.3
36    STU1037    Nikhil Menon      Male       Electronics  22.0        74.8
42    STU1043     Sneha Varma   female       Data Science  19.0        74.4
43    STU1044       Rahul Das    Female  Computer Science  22.0        70.9
47    STU1048     Priya Kumar      Male      Data Science  25.0        64.6
50    STU1051     Gokul Menon      Male      Data Science  25.0        70.9
59    STU1060      Asha Menon      Male      Data Science  19.0        56.3
64    STU1065    Rohan Sharma      Male  Computer Science  19.0        64.4
67    STU1068        Maya Das    Female  Computer Science  23.0        66.7
71    STU1072    Vivek Pillai      Male          Commerce  24.0        71.5

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
2           79.9       80.4          65.3         68.0         67.1
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
8           94.8       86.0          87.7        100.0         83.0
9           79.6       85.0          74.1         80.5         73.8
11          80.4       78.0          88.9         77.1         86.9
15          55.9       69.3          67.1         58.4         58.2
19          65.8       60.9          49.8         44.8         54.6
25          91.7       64.5          83.5         73.7         69.4
36          69.5       60.7          64.6         81.6         69.1
42          71.8       79.1          69.8         95.9          NaN
43          68.0       67.3          83.6         76.7         77.3
47          80.6       67.0          71.2         80.2         77.3
50          68.6       81.0          64.0         63.0         70.5
59         100.0       85.0          87.4         57.4         87.9
64          96.5       69.3          86.7         80.7         83.5
67          83.4       79.6          89.3         83.6         83.7
71          59.0       58.2          56.3         48.9         56.6

In [92]:
score=df[(df['Department']=='Data Science') & (df['Final_Score']>80)]
print(score)

   Student_ID          Name  Gender    Department   Age  Attendance  \
4     STU1005     Asha Nair  Female  Data Science  22.0        71.4
8     STU1009    Diya Menon    Male  Data Science  25.0        64.4
10    STU1011      Diya Das  Female  Data Science  20.0       100.0
16    STU1017  Rahul Thomas  Female  Data Science  25.0        78.3
48    STU1049   Asha Sharma    Male  Data Science  22.0        91.3
55    STU1056   Vivek Varma    Male  Data Science  22.0        81.0
59    STU1060    Asha Menon    Male  Data Science  19.0        56.3

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
4           90.1       82.9          72.4         87.7         81.9
8           94.8       86.0          87.7        100.0         83.0
10         100.0       93.2         100.0         89.3         91.9
16          80.8       99.4          77.2        100.0         91.1
48          88.9       95.0           NaN         94.5         97.0
55          87.0       95.1          88.4         75.7         93.3
59         100.0       85.0          87.4         57.4         87.9

In [94]:
df.sort_values(by='Final_Score',ascending=False)
print(df)

   Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
1     STU1002    Kiran Pillai    Male  Computer Science  24.0        75.5
2     STU1003  Fathima Joseph  Female       Electronics  21.0        60.5
3     STU1004    Rahul Sharma  Female      Data Science  25.0        80.4
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
..        ...             ...     ...               ...   ...         ...
75    STU1076     Priya Kumar  Female  Computer Science  24.0        99.3
76    STU1077      Amal Kumar    Male      Data Science   NaN        93.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
78    STU1079    Meera Thomas    Male       Electronics  23.0        99.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score
0           89.4       86.3          81.9         76.7         82.7
1           70.3       63.1          65.1         62.3         60.3
2           79.9       80.4          65.3         68.0         67.1
3           65.8       50.7          52.6         48.8         57.2
4           90.1       82.9          72.4         87.7         81.9
..           ...        ...           ...          ...          ...
75          46.9       57.6          29.5         57.1         47.2
76          45.8       43.4          58.1         38.8         43.5
77          70.4       75.7          98.2         76.7         75.2
78          64.6       66.5          61.8         52.5         63.4
79          80.5       94.3          58.6         74.9         78.6

[80 rows x 11 columns]

In [102]:
#Q13
df['Average_Technical_Score']=df[['Python_Score','SQL_Score','Pandas_Score','NumPy_Score']].mean(axis=1)

df['Performance']=np.where(df['Average_Technical_Score']>=90,'Excellent',
np.where(df['Average_Technical_Score']>=75,'Good',
np.where(df['Average_Technical_Score']>=60,'Average','Needs Improvement')))

df

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score,Average_Technical_Score,Performance
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7,83.575,Good
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3,65.200,Average
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1,73.400,Average
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2,54.475,Needs Improvement
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9,83.275,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2,47.775,Needs Improvement
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5,46.525,Needs Improvement
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2,80.250,Good
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4,61.350,Average
79,STU1080,Diya Varma,Male,Electronics,19.0,86.4,80.5,94.3,58.6,74.9,78.6,77.075,Good

In [109]:
#Q14
print('Number of students: ' ,df['Department'].value_counts())
print('Average Final Score: ' ,df.groupby('Department')['Final_Score'].mean())
print('Maximum Final Score: ' ,df.groupby('Department')['Final_Score'].max())
print('Minimum Final Score: ' ,df.groupby('Department')['Final_Score'].min())

Number of students:  Department
Computer Science    29
Data Science        27
Electronics         13
Commerce             8
 Data Science        1
data science         1
Computer science     1
Name: count, dtype: int64
Average Final Score:  Department
 Data Science       55.100000
Commerce            67.825000
Computer Science    71.479310
Computer science    46.700000
Data Science        71.324000
Electronics         72.846154
data science        66.900000
Name: Final_Score, dtype: float64
Maximum Final Score:  Department
 Data Science       55.1
Commerce            83.7
Computer Science    96.0
Computer science    46.7
Data Science        97.0
Electronics         86.9
data science        66.9
Name: Final_Score, dtype: float64
Minimum Final Score:  Department
 Data Science       55.1
Commerce            54.6
Computer Science    40.6
Computer science    46.7
Data Science        43.5
Electronics         51.2
data science        66.9
Name: Final_Score, dtype: float64

In [113]:
#Q15
final_scores = df['Final_Score'].to_numpy()


mean = np.nanmean(final_scores)
median = np.nanmedian(final_scores)
std = np.nanstd(final_scores)
p25 = np.nanpercentile(final_scores, 25)
p75 = np.nanpercentile(final_scores, 75)

print(f"Mean: {mean:.2f}")
print(f"Median: {median:.2f}")
print(f"Standard Deviation: {std:.2f}")
print(f"25th Percentile: {p25:.2f}")
print(f"75th Percentile: {p75:.2f}")


above_mean_students = df[df['Final_Score'] > mean]
print(f"\nNumber of students above the mean: {len(above_mean_students)}")
print(above_mean_students)

Mean: 70.70
Median: 70.95
Standard Deviation: 13.96
25th Percentile: 60.45
75th Percentile: 82.28

Number of students above the mean: 42
   Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4
6     STU1007     Akhil Varma    Male       Electronics  22.0        73.2
7     STU1008     Akhil Varma    Male  Computer Science  20.0        81.1
8     STU1009      Diya Menon    Male      Data Science  25.0        64.4
9     STU1010    Gokul Pillai  Female  Computer Science  19.0        67.3
10    STU1011        Diya Das  Female      Data Science  20.0       100.0
11    STU1012      Arun Reddy    Male       Electronics  20.0        69.1
16    STU1017    Rahul Thomas  Female      Data Science  25.0        78.3
17    STU1018      Priya Nair    Male      Data Science  19.0        85.4
20    STU1021      Arun Varma  Female          Commerce  25.0        79.5
23    STU1024  Fathima Joseph  Female          Commerce  23.0        78.2
24    STU1025     Kiran Varma  Female       Electronics  21.0        80.7
27    STU1028     Nikhil Nair  Female      Data Science  24.0        79.3
30    STU1031      Amal Varma  Female  Computer Science  19.0        86.7
33    STU1034        Amal Das    Male  Computer Science  19.0        85.5
35    STU1036      Maya Menon  Female       Electronics  19.0        82.0
37    STU1038    Kiran Pillai  Female       Electronics  25.0        85.2
39    STU1040    Rohan Sharma  Female  Computer Science  21.0       100.0
40    STU1041     Amal Pillai  Female  Computer Science  25.0        97.7
41    STU1042     Arun Joseph  Female  Computer Science  21.0        85.9
43    STU1044       Rahul Das  Female  Computer Science  22.0        70.9
46    STU1047       Gokul Das    Male      Data Science  21.0         NaN
47    STU1048     Priya Kumar    Male      Data Science  25.0        64.6
48    STU1049     Asha Sharma    Male      Data Science  22.0        91.3
51    STU1052      Gokul Nair  Female          Commerce  25.0        77.3
52    STU1053      Maya Varma    Male  Computer Science  22.0        84.6
55    STU1056     Vivek Varma    Male      Data Science  22.0        81.0
56    STU1057    Rohan Pillai  Female          Commerce  20.0        79.5
57    STU1058     Diya Thomas  Female  Computer Science  23.0        83.5
58    STU1059       Anu Menon    Male       Electronics  24.0        96.7
59    STU1060      Asha Menon    Male      Data Science  19.0        56.3
60    STU1061  Fathima Sharma    Male  Computer Science  24.0        79.6
61    STU1062    Kiran Pillai  Female  Computer Science  19.0        83.8
64    STU1065    Rohan Sharma    Male  Computer Science  19.0        64.4
66    STU1067    Rahul Thomas    Male      Data Science   NaN        99.3
67    STU1068        Maya Das  Female  Computer Science  23.0        66.7
72    STU1073   Swathi Joseph    Male      Data Science  22.0        78.7
73    STU1074       Anu Kumar  Female  Computer Science  22.0        95.0
74    STU1075      Gokul Nair  Female      Data Science  23.0        87.8
77    STU1078  Fathima Sharma    Male  Computer Science  19.0        86.4
79    STU1080      Diya Varma    Male       Electronics  19.0        86.4

    Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score  \
0           89.4       86.3          81.9         76.7         82.7
4           90.1       82.9          72.4         87.7         81.9
6           81.7       82.2          81.5         64.2         77.0
7           72.1       80.4          72.9         73.5         79.2
8           94.8       86.0          87.7        100.0         83.0
9           79.6       85.0          74.1         80.5         73.8
10         100.0       93.2         100.0         89.3         91.9
11          80.4       78.0          88.9         77.1         86.9
16          80.8       99.4          77.2        100.0         91.1
17          62.6       81.6          79.6         75.5         75.1
20           NaN       67.6          74.3         75.3         73.2
23          87.7       71.0          88.5         74.8         83.7
24          87.5       67.1          84.5         96.1         77.3
27          70.3       82.0          64.4         72.8         77.1
30          86.9       64.3         100.0         89.2         85.5
33          94.4       81.6          71.3         81.5         84.3
35          95.3       93.4         100.0         62.5         84.2
37          87.8       78.3          85.5         82.7         82.4
39          68.9       79.8          66.1         66.4         78.5
40          94.3       91.0          73.1         91.2         94.5
41          71.2       76.1          70.8          NaN         77.9
43          68.0       67.3          83.6         76.7         77.3
46          69.5       59.3          75.2         75.2         74.8
47          80.6       67.0          71.2         80.2         77.3
48          88.9       95.0           NaN         94.5         97.0
51          80.4       85.3          96.7         83.5         79.3
52          71.9       73.4          70.0         67.2         71.0
55          87.0       95.1          88.4         75.7         93.3
56          72.1       66.9          61.8         72.3         75.2
57          93.1       78.8          91.6         83.8         92.3
58          99.7       77.1          68.9         89.7         84.9
59         100.0       85.0          87.4         57.4         87.9
60          80.8       63.1          71.1         67.9         70.8
61         100.0      100.0          89.4         91.4         96.0
64          96.5       69.3          86.7         80.7         83.5
66           NaN       56.2          69.0         81.5         70.7
67          83.4       79.6          89.3         83.6         83.7
72          76.4       77.5          73.6         65.6         73.5
73          95.3       67.7          92.4         81.4         83.4
74          85.4       80.0          65.2         70.4         70.9
77          70.4       75.7          98.2         76.7         75.2
79          80.5       94.3          58.6         74.9         78.6

    Average_Technical_Score Performance
0                    83.575        Good
4                    83.275        Good
6                    77.400        Good
7                    74.725     Average
8                    92.125   Excellent
9                    79.800        Good
10                   95.625   Excellent
11                   81.100        Good
16                   89.350        Good
17                   74.825     Average
20                   72.400     Average
23                   80.500        Good
24                   83.800        Good
27                   72.375     Average
30                   85.100        Good
33                   82.200        Good
35                   87.800        Good
37                   83.575        Good
39                   70.300     Average
40                   87.400        Good
41                   72.700     Average
43                   73.900     Average
46                   69.800     Average
47                   74.750     Average
48                   92.800   Excellent
51                   86.475        Good
52                   70.625     Average
55                   86.550        Good
56                   68.275     Average
57                   86.825        Good
58                   83.850        Good
59                   82.450        Good
60                   70.725     Average
61                   95.200   Excellent
64                   83.300        Good
66                   68.900     Average
67                   83.975        Good
72                   73.275     Average
73                   84.200        Good
74                   75.250        Good
77                   80.250        Good
79                   77.075        Good

In [118]:
#Q16
print("Missing values:\n", df.isnull().sum())
df.fillna({'Age': df.Age.mean()}, inplace=True)
df.fillna({'Attendance': df.Attendance.mean()}, inplace=True)
df.fillna({'Python_Score': df.Python_Score.mean()}, inplace=True)
df.fillna({'Pandas_Score': df.Pandas_Score.mean()}, inplace=True)
df.fillna({'NumPy_Score': df.NumPy_Score.mean()}, inplace=True)
df.fillna({'Final_Score':df.Final_Score.mean()}, inplace=True)
print(df)

Missing values:
 Student_ID                 0
Name                       0
Gender                     0
Department                 0
Age                        0
Attendance                 0
Python_Score               0
SQL_Score                  0
Pandas_Score               0
NumPy_Score                0
Final_Score                0
Average_Technical_Score    0
Performance                0
dtype: int64
   Student_ID            Name  Gender        Department        Age  \
0     STU1001     Rahul Varma    Male  Computer Science  25.000000
1     STU1002    Kiran Pillai    Male  Computer Science  24.000000
2     STU1003  Fathima Joseph  Female       Electronics  21.000000
3     STU1004    Rahul Sharma  Female      Data Science  25.000000
4     STU1005       Asha Nair  Female      Data Science  22.000000
..        ...             ...     ...               ...        ...
75    STU1076     Priya Kumar  Female  Computer Science  24.000000
76    STU1077      Amal Kumar    Male      Data Science  22.012987
77    STU1078  Fathima Sharma    Male  Computer Science  19.000000
78    STU1079    Meera Thomas    Male       Electronics  23.000000
79    STU1080      Diya Varma    Male       Electronics  19.000000

    Attendance  Python_Score  SQL_Score  Pandas_Score  NumPy_Score  \
0         74.7          89.4       86.3          81.9         76.7
1         75.5          70.3       63.1          65.1         62.3
2         60.5          79.9       80.4          65.3         68.0
3         80.4          65.8       50.7          52.6         48.8
4         71.4          90.1       82.9          72.4         87.7
..         ...           ...        ...           ...          ...
75        99.3          46.9       57.6          29.5         57.1
76        93.8          45.8       43.4          58.1         38.8
77        86.4          70.4       75.7          98.2         76.7
78        99.4          64.6       66.5          61.8         52.5
79        86.4          80.5       94.3          58.6         74.9

    Final_Score  Average_Technical_Score        Performance
0          82.7                   83.575               Good
1          60.3                   65.200            Average
2          67.1                   73.400            Average
3          57.2                   54.475  Needs Improvement
4          81.9                   83.275               Good
..          ...                      ...                ...
75         47.2                   47.775  Needs Improvement
76         43.5                   46.525  Needs Improvement
77         75.2                   80.250               Good
78         63.4                   61.350            Average
79         78.6                   77.075               Good

[80 rows x 13 columns]

In [120]:
df['Average_Score']=df[['Python_Score','SQL_Score','Pandas_Score','NumPy_Score']].mean(axis=1)
df['Pass_Status']=np.where(df['Average_Score']>=50,'Pass','Fail')
df

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score,Average_Technical_Score,Performance,Average_Score,Pass_Status
0,STU1001,Rahul Varma,Male,Computer Science,25.000000,74.7,89.4,86.3,81.9,76.7,82.7,83.575,Good,83.575,Pass
1,STU1002,Kiran Pillai,Male,Computer Science,24.000000,75.5,70.3,63.1,65.1,62.3,60.3,65.200,Average,65.200,Pass
2,STU1003,Fathima Joseph,Female,Electronics,21.000000,60.5,79.9,80.4,65.3,68.0,67.1,73.400,Average,73.400,Pass
3,STU1004,Rahul Sharma,Female,Data Science,25.000000,80.4,65.8,50.7,52.6,48.8,57.2,54.475,Needs Improvement,54.475,Pass
4,STU1005,Asha Nair,Female,Data Science,22.000000,71.4,90.1,82.9,72.4,87.7,81.9,83.275,Good,83.275,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.000000,99.3,46.9,57.6,29.5,57.1,47.2,47.775,Needs Improvement,47.775,Fail
76,STU1077,Amal Kumar,Male,Data Science,22.012987,93.8,45.8,43.4,58.1,38.8,43.5,46.525,Needs Improvement,46.525,Fail
77,STU1078,Fathima Sharma,Male,Computer Science,19.000000,86.4,70.4,75.7,98.2,76.7,75.2,80.250,Good,80.250,Pass
78,STU1079,Meera Thomas,Male,Electronics,23.000000,99.4,64.6,66.5,61.8,52.5,63.4,61.350,Average,61.350,Pass
79,STU1080,Diya Varma,Male,Electronics,19.000000,86.4,80.5,94.3,58.6,74.9,78.6,77.075,Good,77.075,Pass

In [121]:
print('Average_Score: ' ,df.groupby('Department')['Average_Score'].max())

Average_Score:  Department
 Data Science       59.20000
Commerce            86.47500
Computer Science    95.20000
Computer science    53.84359
Data Science        95.62500
Electronics         87.80000
data science        64.72500
Name: Average_Score, dtype: float64

In [122]:
print('Average_Attendance: ' ,df.groupby('Department')['Attendance'].mean())

Average_Attendance:  Department
 Data Science       76.700000
Commerce            77.437500
Computer Science    82.768025
Computer science    92.100000
Data Science        82.076768
Electronics         80.576923
data science        81.672727
Name: Attendance, dtype: float64